/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAssignment2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;



/**
 *
 * @author student
 */
public class CarDBM extends javax.swing.JFrame {

    /**
     * Creates new form SecondJFrame
     */
    public CarDBM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        logo = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        SearchBTN = new javax.swing.JButton();
        AddBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        DeleteBTN = new javax.swing.JButton();
        costinbox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        colourbox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idbox = new javax.swing.JTextField();
        Makebox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modelbox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        milagebox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        costoutbox = new javax.swing.JTextField();
        doorbox = new javax.swing.JComboBox<>();
        yearbox1 = new javax.swing.JComboBox<>();
        taxbox1 = new javax.swing.JSlider();
        taxNumber = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ExitBTN = new javax.swing.JButton();
        view = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbtable = new javax.swing.JTextArea();
        View = new javax.swing.JButton();
        help = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        emailH = new javax.swing.JTextField();
        sendH = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        stats = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        items = new javax.swing.JTextField();
        average = new javax.swing.JTextField();
        StatsBTN = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Average2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AverageTax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 131, 69));

        jTabbedPane1.setBackground(java.awt.SystemColor.activeCaption);
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        logo.setBackground(java.awt.SystemColor.activeCaption);

        jLabel17.setBackground(java.awt.SystemColor.activeCaption);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIAssignment2/car.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Welcome");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", logo);

        edit.setBackground(java.awt.SystemColor.activeCaption);
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));

        SearchBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        SearchBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SearchBTN.setText("search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        AddBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        AddBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        ClearBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ClearBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearBTN.setText("clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        UpdateBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBTN.setText("update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        DeleteBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        DeleteBTN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBTN.setText("delete");
        DeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBTNActionPerformed(evt);
            }
        });

        costinbox.setToolTipText("Enter the amount the car was bought into the shop for ");
        costinbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costinboxKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tax");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Doors");

        colourbox.setToolTipText("enter the colour of the car \n");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Colour");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CostIn");

        idbox.setToolTipText("Please Enter the cars ID here ");
        idbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idboxKeyPressed(evt);
            }
        });

        Makebox.setToolTipText("Please enter the make of the car here ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Make");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Model");

        modelbox.setToolTipText("please enter cars model here  ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Year");

        milagebox.setToolTipText("Enter the milage on the car ");
        milagebox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                milageboxKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Milage");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("CostOut");

        costoutbox.setToolTipText("Enter the amount we are selling the car for ");
        costoutbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoutboxKeyPressed(evt);
            }
        });

        doorbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8" }));
        doorbox.setToolTipText("select the amount of doors ");

        yearbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010" }));
        yearbox1.setToolTipText("Select the year the car was made ");

        taxbox1.setMajorTickSpacing(200);
        taxbox1.setMaximum(2000);
        taxbox1.setMinimum(50);
        taxbox1.setMinorTickSpacing(50);
        taxbox1.setPaintLabels(true);
        taxbox1.setPaintTicks(true);
        taxbox1.setToolTipText("select the tax of the car");
        taxbox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                taxbox1StateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Welcome Add/Remove/Update/Delete records here.");

        ExitBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editLayout = new javax.swing.GroupLayout(edit);
        edit.setLayout(editLayout);
        editLayout.setHorizontalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(milagebox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idbox, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(Makebox)
                                    .addComponent(modelbox))))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxbox1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(costoutbox)
                            .addComponent(costinbox, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doorbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourbox)))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ExitBTN))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 131, Short.MAX_VALUE))
        );

        editLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel7, jLabel8});

        editLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {colourbox, costinbox, costoutbox, doorbox, taxNumber, taxbox1});

        editLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddBTN, ClearBTN, DeleteBTN, ExitBTN, SearchBTN, UpdateBTN});

        editLayout.setVerticalGroup(
            editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Makebox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(modelbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(yearbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(milagebox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3))
                    .addGroup(editLayout.createSequentialGroup()
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(doorbox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(taxbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costinbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoutbox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        editLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {colourbox, costinbox, costoutbox, doorbox, taxbox1});

        editLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddBTN, ClearBTN, DeleteBTN, ExitBTN, SearchBTN, UpdateBTN});

        jTabbedPane1.addTab("Create", edit);

        view.setBackground(java.awt.SystemColor.activeCaption);

        dbtable.setEditable(false);
        dbtable.setBackground(java.awt.SystemColor.activeCaption);
        dbtable.setColumns(20);
        dbtable.setRows(5);
        jScrollPane1.setViewportView(dbtable);

        View.setText("View db");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addGroup(viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(View)))
                .addContainerGap())
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View)
                .addGap(78, 78, 78))
        );

        jTabbedPane1.addTab("View", view);

        help.setBackground(java.awt.SystemColor.activeCaption);

        jLabel6.setText("Enter Email");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIAssignment2/email.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Please tell us your issue below");

        javax.swing.GroupLayout helpLayout = new javax.swing.GroupLayout(help);
        help.setLayout(helpLayout);
        helpLayout.setHorizontalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(emailH))
                    .addComponent(jScrollPane2)
                    .addComponent(sendH, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(send)
                .addGap(20, 20, 20))
            .addGroup(helpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        helpLayout.setVerticalGroup(
            helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(emailH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(helpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(helpLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sendH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(send))
        );

        jTabbedPane1.addTab("Help", help);

        stats.setBackground(java.awt.SystemColor.activeCaption);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No of cars in db");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Average costout of car");

        StatsBTN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        StatsBTN.setText("check");
        StatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsBTNActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Average costin ");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Average Tax");

        javax.swing.GroupLayout statsLayout = new javax.swing.GroupLayout(stats);
        stats.setLayout(statsLayout);
        statsLayout.setHorizontalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsLayout.createSequentialGroup()
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AverageTax, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Average2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(items, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(average, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(statsLayout.createSequentialGroup()
                        .addGap(766, 766, 766)
                        .addComponent(StatsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        statsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel14, jLabel16, jLabel4, jLabel5});

        statsLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Average2, AverageTax, average, items});

        statsLayout.setVerticalGroup(
            statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(items, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(average, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Average2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(statsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AverageTax, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(StatsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        statsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Average2, AverageTax, average, items});

        statsLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel14, jLabel16, jLabel4, jLabel5});

        jTabbedPane1.addTab("Stats", stats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String url = "jdbc:sqlite:c:/mydb/Dddillon4.db";
    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        //Start of text area view button
        dbtable.setText(null); //blank the text area
       dbtable.append("ID \t Make \t Model \t Year \t Milage \t Colour \t Doors \t CostIn \t CostOut \t CarTax  \n"); //set heading for table
 
     
        
      
       
        try (Connection conn = DriverManager.getConnection(url)) {
            //Statement – Used to execute string-based SQL queries
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM cars"); 
            while(rs.next()){ 
                String carid = rs.getString("ID"); 
                String carmake = rs.getString("Make"); 
                String carmodel = rs.getString("Model");
                String caryear = rs.getString("Year");
                String carmilage = rs.getString("Milage");
                String carcolour = rs.getString("Colour");
                String cardoors = rs.getString("Doors");
                String costin = rs.getString("CostIn");
                String costout = rs.getString("CostOut");
                String cartax = rs.getString("Tax");
                
               
              dbtable.append(carid + "\t" + carmake + "\t" + carmodel +  "\t" + caryear+  "\t" + carmilage + "\t" + carcolour + "\t" + cardoors +"\t" + costin+ "\t" + costout+ "\t" + cartax +"\t"+ "\n"); // for every entry in the table append to text area
            }//end while    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error"); 
        }//end try catch
        //end of text area view button	

    }//GEN-LAST:event_ViewActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        //Start of search button
        //try and make a connection to the DB using the global URL variable
        //The connection and statements objects might be better if global?
        try (Connection conn = DriverManager.getConnection(url)){  
            String str = idbox.getText();  
            //PreparedStatement – Used to execute parameterized SQL queries
            PreparedStatement st = conn.prepareStatement("select * from cars where id=?");  
            st.setString(1, str); //pass id string to statement, why 1? multiple statements? location?
            //Excuting Query  
            ResultSet rs = st.executeQuery(); //get result set rs by executing the Prepared Statement
            if (rs.next()) { //iterate rs
                 String s = rs.getString(1); //get id from rs, save as s 
                String s1 = rs.getString(2); 
                String s2 = rs.getString(3); 
                String s3 = rs.getString(4); 
                String s4 = rs.getString(5); 
                String s5 = rs.getString(6); 
                String s6 = rs.getString(7); 
                String s7 = rs.getString(8); 
                String s8 = rs.getString(9); 
                Integer s9 = rs.getInt(10); 
                //Sets Records in TextFields.  
                idbox.setText(s); //set id in textbox  
                Makebox.setText(s1);  //set make in textbox 
                modelbox.setText(s2);  //set model in textbox 
               yearbox1.setSelectedItem(s3); //set year in textbox  
                milagebox.setText(s4);  //set milage in textbox 
                colourbox.setText(s5);  //set colour in textbox
                doorbox.setSelectedItem(s6);  //set dorrs in textbox
                costoutbox.setText(s8);  //set costout in textbox
               costinbox.setText(s7);  //set costin in textbox
                taxbox1.setValue(s9);  //set tax in textbox
            } else {  
                JOptionPane.showMessageDialog(null, "ERROR"); 
            } //end if else  
            //Create Exception Handler  
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,"Error"); //error from try
        }//end try catch
        //end of search button

    }//GEN-LAST:event_SearchBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
               //Start of Add button
   
        try (Connection conn = DriverManager.getConnection(url)){  
          
            Statement statement = conn.createStatement();
           
      statement.execute("INSERT INTO cars VALUES('" + idbox.getText() + "' , '" + Makebox.getText() + "' , '" + modelbox.getText()+ "' , '" + yearbox1.getSelectedItem()+ "' , '"+ milagebox.getText() + "' , '" + colourbox.getText() + "' , '" + doorbox.getSelectedItem()+ "' , '" + costoutbox.getText()+ "' , '"+ costinbox.getText() + "' , '" + taxbox1.getValue() + "')");
  JOptionPane.showMessageDialog(null, "Car Added"); 
  
            statement.close(); 
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null, "ID cannot be the same"); 
        } //end try catch
        //end of insert button


    }//GEN-LAST:event_AddBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
        //clear button
        idbox.setText(null);
       Makebox.setText(null);
      modelbox.setText(null);
      yearbox1.setSelectedItem(2022);
       milagebox.setText(null);
        colourbox.setText(null);
         doorbox.setSelectedItem(2);
          costoutbox.setText(null);
           costinbox.setText(null);
           taxbox1.setValue(200);
            
       
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        //Start of update button
              
        
        try (Connection conn = DriverManager.getConnection(url)){ 
         
            Statement statement = conn.createStatement();
          
            
             String query ="UPDATE cars SET make='" + Makebox.getText() + "', model='" + modelbox.getText() + "', year='" + yearbox1.getSelectedItem() + "', milage='" + milagebox.getText() + "', colour='" + colourbox.getText() + "', doors='" + doorbox.getSelectedItem()+ "', costin='" + costoutbox.getText() + "', costout='" + costinbox.getText() + "', tax='" + taxbox1.getValue() + " 'WHERE id='" + idbox.getText() +"' ";
         statement.execute(query);
            JOptionPane.showMessageDialog(null, "Car Updated");
            statement.close(); 
            conn.close();
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,"Error");
        } //end try catch
        //end of update button

    }//GEN-LAST:event_UpdateBTNActionPerformed

             
    
    private void DeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBTNActionPerformed
                //Start of delete button
      
        try (Connection conn = DriverManager.getConnection(url)){ 
          
            Statement statement = conn.createStatement();
           
            statement.executeUpdate("DELETE FROM cars WHERE id=" + idbox.getText() + "");  
            JOptionPane.showMessageDialog(null, "Car deleted"); 
            statement.close();
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,"Error ID not Found"); 
        } //end try catch
        //end of delete button

    }//GEN-LAST:event_DeleteBTNActionPerformed

    private void StatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsBTNActionPerformed
        //start query button
       
        String total = DBQueries.count(); //run count query from DBQueries.java file in project package
        items.setText(total); 
        
        String itemaverage = DBQueries.average(); 
        average.setText(itemaverage);
        
        String itemaverage2 = DBQueries.average2(); 
        Average2.setText(itemaverage2); 
        
        String itemaverage3 = DBQueries.average3(); 
        AverageTax.setText(itemaverage3); 
        
        //close queries button

    }//GEN-LAST:event_StatsBTNActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
       String email = emailH.getText();
        String regEx = "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}\\b";

        Pattern p = Pattern.compile(regEx);
        Matcher m = p.matcher(email);

        if(m.find()) 
        {
         sendH.setText("Thank you a member of our team will be in contact with you soon"); }
        else
        {
         sendH.setText("Invalid Email address: Email Not Sent");
        }
    }//GEN-LAST:event_sendActionPerformed

    private void idboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idboxKeyPressed
char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    idbox.setEditable(false);
    idbox.setText("Please Enter Number Only");
}else
{
    idbox.setEditable(true);
    
    }//GEN-LAST:event_idboxKeyPressed
    }
    private void taxbox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_taxbox1StateChanged
       taxNumber.setText("Tax =  " + (taxbox1).getValue());
    }//GEN-LAST:event_taxbox1StateChanged

    private void milageboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_milageboxKeyPressed
        char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    milagebox.setEditable(false);
    milagebox.setText("Please Enter Number Only");
}else
{
    milagebox.setEditable(true);
}
    }//GEN-LAST:event_milageboxKeyPressed

    private void costinboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costinboxKeyPressed
       char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    costinbox.setEditable(false);
    costinbox.setText("Please Enter Number Only");
}else
{
    costinbox.setEditable(true);
}
    }//GEN-LAST:event_costinboxKeyPressed

    private void costoutboxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoutboxKeyPressed
         char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    costoutbox.setEditable(false);
    costoutbox.setText("Please Enter Number Only");
}else
{
    costoutbox.setEditable(true);
}
    }//GEN-LAST:event_costoutboxKeyPressed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
          this.dispose(); //dispose of the first frame
Managerhome.main(null); 
    }//GEN-LAST:event_ExitBTNActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarDBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarDBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarDBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarDBM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarDBM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JTextField Average2;
    private javax.swing.JTextField AverageTax;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton DeleteBTN;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JTextField Makebox;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton StatsBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton View;
    private javax.swing.JTextField average;
    private javax.swing.JTextField colourbox;
    private javax.swing.JTextField costinbox;
    private javax.swing.JTextField costoutbox;
    private javax.swing.JTextArea dbtable;
    private javax.swing.JComboBox<String> doorbox;
    private javax.swing.JPanel edit;
    private javax.swing.JTextField emailH;
    private javax.swing.JPanel help;
    private javax.swing.JTextField idbox;
    private javax.swing.JTextField items;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel logo;
    private javax.swing.JTextField milagebox;
    private javax.swing.JTextField modelbox;
    private javax.swing.JButton send;
    private javax.swing.JTextField sendH;
    private javax.swing.JPanel stats;
    private javax.swing.JLabel taxNumber;
    private javax.swing.JSlider taxbox1;
    private javax.swing.JPanel view;
    private javax.swing.JComboBox<String> yearbox1;
    // End of variables declaration//GEN-END:variables
}
