/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAssignment2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dillon
 */
public class CustomerDB extends javax.swing.JFrame {

    /**
     * Creates new form CustomerDB
     */
    public CustomerDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CustomerIDBox = new javax.swing.JTextField();
        CustomerNameBox = new javax.swing.JTextField();
        CustomerEmailBox = new javax.swing.JTextField();
        CustomerPhoneBox = new javax.swing.JTextField();
        CustomerAddressBox = new javax.swing.JTextField();
        AddBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        RemoveBtn = new javax.swing.JButton();
        SearchBTN = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CusTable = new javax.swing.JTextArea();
        ViewCus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Phone No");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Address");

        CustomerIDBox.setToolTipText("Enter ID");
        CustomerIDBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CustomerIDBoxKeyPressed(evt);
            }
        });

        CustomerNameBox.setToolTipText("Enter Customers Name ");

        CustomerEmailBox.setToolTipText("Enter Customers Email ");

        CustomerPhoneBox.setToolTipText("Enter Customers Phone number");
        CustomerPhoneBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CustomerPhoneBoxKeyPressed(evt);
            }
        });

        CustomerAddressBox.setToolTipText("Eneter customers address");

        AddBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        UpdateBTN.setText("Update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        RemoveBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        RemoveBtn.setText("Remove");
        RemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBtnActionPerformed(evt);
            }
        });

        SearchBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        jButton5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ExitBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIAssignment2/car - Copy - Copy.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Below you can Add/remove/edit customer details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerPhoneBox)
                            .addComponent(CustomerIDBox)
                            .addComponent(CustomerNameBox)
                            .addComponent(CustomerEmailBox)
                            .addComponent(CustomerAddressBox)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBTN)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveBtn)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBTN)
                        .addGap(18, 18, 18)
                        .addComponent(AddBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddBTN, ExitBTN, RemoveBtn, SearchBTN, UpdateBTN, jButton5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerIDBox)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(CustomerNameBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerEmailBox)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerPhoneBox)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CustomerAddressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBTN)
                    .addComponent(UpdateBTN)
                    .addComponent(RemoveBtn)
                    .addComponent(SearchBTN)
                    .addComponent(jButton5)
                    .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CustomerEmailBox, CustomerIDBox, CustomerNameBox, CustomerPhoneBox, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddBTN, ExitBTN, RemoveBtn, SearchBTN, UpdateBTN, jButton5});

        jTabbedPane1.addTab("Add", jPanel1);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        CusTable.setEditable(false);
        CusTable.setBackground(java.awt.SystemColor.activeCaption);
        CusTable.setColumns(20);
        CusTable.setRows(5);
        jScrollPane1.setViewportView(CusTable);

        ViewCus.setText("View");
        ViewCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewCus)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219)
                .addComponent(ViewCus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View DB", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String url = "jdbc:sqlite:c:/mydb/Dddillon4.db";
    private void ViewCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCusActionPerformed
        //Start of text area view button
        CusTable.setText(null); //blank the text area
       CusTable.append("ID \t Name \t Email \t \t Phone No \t Address    \n"); //set heading for table
 
     
        
      
       
        try (Connection conn = DriverManager.getConnection(url)) {
            //Statement – Used to execute string-based SQL queries
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM customers"); 
            while(rs.next()){ 
                String cusid = rs.getString("CustomerID"); 
                String cusname = rs.getString("CustomerName"); 
                String cusemail = rs.getString("CustomerEmail");
                String cusphone = rs.getString("CustomerPhoneNo");
                String cusaddress = rs.getString("CustomerAddress");
               
               
                
               
              CusTable.append(cusid + "\t" + cusname + "\t" + cusemail +  "\t" + cusphone+  "\t" + cusaddress + "\t" +    "\n"); // for every entry in the table append to text area
            }//end while    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,(e.getMessage())); 
        }//end try catch
        //end of text area view button	
    }//GEN-LAST:event_ViewCusActionPerformed

    
    
    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
 //Start of search button
        //try and make a connection to the DB using the global URL variable
        //The connection and statements objects might be better if global?
        try (Connection conn = DriverManager.getConnection(url)){  
            String str = CustomerIDBox.getText();  
            //PreparedStatement – Used to execute parameterized SQL queries
            PreparedStatement st = conn.prepareStatement("select * from customers where customerid=?");  
            st.setString(1, str); //pass id string to statement, why 1? multiple statements? location?
            //Excuting Query  
            ResultSet rs = st.executeQuery(); //get result set rs by executing the Prepared Statement
            if (rs.next()) { //iterate rs
                 String s = rs.getString(1); //get id from rs, save as s 
                String s1 = rs.getString(2); 
                String s2 = rs.getString(3); 
                String s3 = rs.getString(4); 
                String s4 = rs.getString(5); 
                
              
                //Sets Records in TextFields.  
                CustomerIDBox.setText(s); //set id in textbox  
                CustomerNameBox.setText(s1);  //set make in textbox 
                CustomerEmailBox.setText(s2); 
                CustomerPhoneBox.setText(s3);  //set milage in textbox 
                CustomerAddressBox.setText(s4);  //set model in textbox 
                
                
            } else {  
                JOptionPane.showMessageDialog(null, "ERROR"); 
            } //end if else  
            //Create Exception Handler  
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage())); //error from try
        }//end try catch
        //end of search button
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
         //Start of Add button
   
        try (Connection conn = DriverManager.getConnection(url)){  
          
            Statement statement = conn.createStatement();
           
      statement.execute("INSERT INTO customers VALUES('" + CustomerIDBox.getText() + "' , '" + CustomerNameBox.getText() + "' , '" + CustomerEmailBox.getText()+ "' , '" + CustomerPhoneBox.getText()+ "' , '"+ CustomerAddressBox.getText()   + "')");
  JOptionPane.showMessageDialog(null, "customer Added"); 
  
            statement.close(); 
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage())); 
        } //end try catch
        //end of insert button
    }//GEN-LAST:event_AddBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
   //Start of update button
              
        
        try (Connection conn = DriverManager.getConnection(url)){ 
         
            Statement statement = conn.createStatement();
          
            
             String query ="UPDATE customers SET customerid='" + CustomerIDBox.getText() + "', customername='" + CustomerNameBox.getText() + "', customeremail='" + CustomerEmailBox.getText() + "', customerphoneno='" + CustomerPhoneBox.getText() + "', customeraddress='" + CustomerAddressBox.getText() +  " 'WHERE customerid='" + CustomerIDBox.getText() +"' ";
         statement.execute(query);
            JOptionPane.showMessageDialog(null, "Car Updated");
            statement.close(); 
            conn.close();
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage()));
        } //end try catch
        //end of update button
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void RemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBtnActionPerformed
          //Start of delete button
      
        try (Connection conn = DriverManager.getConnection(url)){ 
          
            Statement statement = conn.createStatement();
           
            statement.executeUpdate("DELETE FROM customers WHERE customerid=" + CustomerIDBox.getText() + "");  
            JOptionPane.showMessageDialog(null, "customer deleted"); 
            statement.close();
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,"Error ID not Found"); 
        } //end try catch
        //end of delete button
    }//GEN-LAST:event_RemoveBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       CustomerIDBox.setText(null);
       CustomerNameBox.setText(null);
       CustomerEmailBox.setText(null);   
       CustomerPhoneBox.setText(null);
       CustomerAddressBox.setText(null);
      
               
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
          this.dispose(); //dispose of the first frame
Managerhome.main(null); 
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void CustomerIDBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerIDBoxKeyPressed
           char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    CustomerIDBox.setEditable(false);
    CustomerIDBox.setText("Please Enter Number Only");
}else
{
    CustomerIDBox.setEditable(true);
}
    }//GEN-LAST:event_CustomerIDBoxKeyPressed

    private void CustomerPhoneBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CustomerPhoneBoxKeyPressed
         char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    CustomerPhoneBox.setEditable(false);
    CustomerPhoneBox.setText("Please Enter Number Only");
}else
{
    CustomerPhoneBox.setEditable(true);
}
                                            
    }//GEN-LAST:event_CustomerPhoneBoxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JTextArea CusTable;
    private javax.swing.JTextField CustomerAddressBox;
    private javax.swing.JTextField CustomerEmailBox;
    private javax.swing.JTextField CustomerIDBox;
    private javax.swing.JTextField CustomerNameBox;
    private javax.swing.JTextField CustomerPhoneBox;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton RemoveBtn;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton ViewCus;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
