/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIAssignment2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author dillon
 */
public class ServiceDB extends javax.swing.JFrame {

    /**
     * Creates new form ServiceDB
     */
    public ServiceDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RemoveBTN = new javax.swing.JButton();
        UpdateBTN = new javax.swing.JButton();
        AddBTN = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        NameBox = new javax.swing.JTextField();
        IDBox = new javax.swing.JTextField();
        DateBox = new javax.swing.JTextField();
        CostBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SearchBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbtable = new javax.swing.JTextArea();
        ViewDB = new javax.swing.JButton();
        ExitBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Service Info");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Cost");

        RemoveBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        RemoveBTN.setText("Remove");
        RemoveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBTNActionPerformed(evt);
            }
        });

        UpdateBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        UpdateBTN.setText("Update");
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        AddBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        AddBTN.setText("Add");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBTNActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("ServiceID");

        IDBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDBoxKeyPressed(evt);
            }
        });

        DateBox.setText("DD/MM/YY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Name");

        SearchBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        ClearBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });

        ExitBTN.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        ExitBTN.setText("Exit");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIAssignment2/car - Copy - Copy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBTN)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBTN)
                        .addGap(18, 18, 18)
                        .addComponent(AddBTN)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateBTN)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveBTN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDBox, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CostBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CostBox, DateBox, IDBox, NameBox, jLabel2, jLabel4, jLabel5, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddBTN, ClearBTN, ExitBTN, RemoveBTN, SearchBTN, UpdateBTN});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(IDBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CostBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBTN)
                    .addComponent(SearchBTN)
                    .addComponent(AddBTN)
                    .addComponent(UpdateBTN)
                    .addComponent(RemoveBTN))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CostBox, DateBox, IDBox, NameBox, jLabel2, jLabel4, jLabel5, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddBTN, ClearBTN, ExitBTN, RemoveBTN, SearchBTN, UpdateBTN});

        jTabbedPane1.addTab("Create", jPanel1);

        jPanel2.setBackground(java.awt.SystemColor.activeCaption);

        dbtable.setEditable(false);
        dbtable.setBackground(java.awt.SystemColor.activeCaption);
        dbtable.setColumns(20);
        dbtable.setRows(5);
        jScrollPane1.setViewportView(dbtable);

        ViewDB.setText("View");
        ViewDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDBActionPerformed(evt);
            }
        });

        ExitBTN1.setText("Exit");
        ExitBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ExitBTN1)
                        .addGap(18, 18, 18)
                        .addComponent(ViewDB))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewDB)
                    .addComponent(ExitBTN1))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public String url = "jdbc:sqlite:c:/mydb/Dddillon4.db";
    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
      //Start of search button
        //try and make a connection to the DB using the global URL variable
        //The connection and statements objects might be better if global?
        try (Connection conn = DriverManager.getConnection(url)){  
            String str = IDBox.getText();  
            //PreparedStatement – Used to execute parameterized SQL queries
            PreparedStatement st = conn.prepareStatement("select * from service where serviceid=?");  
            st.setString(1, str); 
            //Excuting Query  
            ResultSet rs = st.executeQuery(); //get result set rs by executing the Prepared Statement
            if (rs.next()) { //iterate rs
                 String s = rs.getString(1); //get id from rs, save as s 
                String s1 = rs.getString(2); 
                String s2 = rs.getString(3); 
                String s3 = rs.getString(4); 
               
              
                //Sets Records in TextFields.  
                IDBox.setText(s); //set id in textbox  
                DateBox.setText(s1); //set make in textbox 
                CostBox.setText(s2); 
               NameBox.setText(s3);   //set milage in textbox 
              
                
            } else {  
                JOptionPane.showMessageDialog(null, "ERROR"); 
            } //end if else  
            //Create Exception Handler  
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage())); //error from try
        }//end try catch
        //end of search button
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void ViewDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDBActionPerformed
         //Start of text area view button
        dbtable.setText(null); //blank the text area
       dbtable.append("ID \t date \t cost \t customername    \n"); //set heading for table
 
     
        
      
       
        try (Connection conn = DriverManager.getConnection(url)) {
            //Statement – Used to execute string-based SQL queries
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM service"); 
            while(rs.next()){ 
                String serid = rs.getString("ServiceID"); 
                String serdate = rs.getString("ServiceDate"); 
                String sercost = rs.getString("ServiceCost");
                String sername = rs.getString("CustomerName");
                
               
                
               
              dbtable.append(serid + "\t" + serdate + "\t" + sercost +  "\t" + sername+  "\t" +   "\n"); // for every entry in the table append to text area
            }//end while    
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,(e.getMessage())); 
        }//end try catch
        //end of text area view button	
    }//GEN-LAST:event_ViewDBActionPerformed

    private void AddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBTNActionPerformed
        //Start of Add button
   
        try (Connection conn = DriverManager.getConnection(url)){  
          
            Statement statement = conn.createStatement();
           
      statement.execute("INSERT INTO service VALUES('" + IDBox.getText() + "' , '" + DateBox.getText() + "' , '" + CostBox.getText()+ "' , '" + NameBox.getText()+ "')");
  JOptionPane.showMessageDialog(null, "service Added"); 
  
            statement.close(); 
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage())); 
        } //end try catch
        //end of insert button
    }//GEN-LAST:event_AddBTNActionPerformed

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
       //Start of update button
              
        
        try (Connection conn = DriverManager.getConnection(url)){ 
         
            Statement statement = conn.createStatement();
          
            
             String query ="UPDATE service SET serviceid='" + IDBox.getText() + "', servicedate='" + DateBox.getText() + "', servicecost='" + CostBox.getText() + "', customername='" + NameBox.getText()+  " 'WHERE serviceid='" + IDBox.getText() +"' ";
         statement.execute(query);
            JOptionPane.showMessageDialog(null, "service Updated");
            statement.close(); 
            conn.close();
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,(e.getMessage()));
        } //end try catch
        //end of update button
    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void RemoveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBTNActionPerformed
        //Start of delete button
      
        try (Connection conn = DriverManager.getConnection(url)){ 
          
            Statement statement = conn.createStatement();
           
            statement.executeUpdate("DELETE FROM service WHERE serviceid=" + IDBox.getText() + "");  
            JOptionPane.showMessageDialog(null, "service deleted"); 
            statement.close();
            conn.close(); 
        } catch (Exception e) {  
            JOptionPane.showMessageDialog(null,"Error ID not Found"); 
        } //end try catch
        //end of delete button
    }//GEN-LAST:event_RemoveBTNActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
         IDBox.setText(null);
       DateBox.setText(null);
      CostBox.setText(null);
      NameBox.setText(null);
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
       this.dispose(); //dispose of the first frame
Managerhome.main(null); 
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void ExitBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTN1ActionPerformed
       this.dispose(); //dispose of the first frame
Managerhome.main(null); 
    }//GEN-LAST:event_ExitBTN1ActionPerformed

    private void IDBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDBoxKeyPressed
        char c = evt.getKeyChar();
if(Character.isLetter(c)) {
    IDBox.setEditable(false);
    IDBox.setText("Please Enter Number Only");
}else
{
    IDBox.setEditable(true);
}
    }//GEN-LAST:event_IDBoxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JTextField CostBox;
    private javax.swing.JTextField DateBox;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton ExitBTN1;
    private javax.swing.JTextField IDBox;
    private javax.swing.JTextField NameBox;
    private javax.swing.JButton RemoveBTN;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton ViewDB;
    private javax.swing.JTextArea dbtable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
